# Generated by Django 5.2.12 on 2026-03-31 04:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('handphone', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('nim', models.CharField(max_length=12)),
                ('timestamp', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_jurusan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kampus_app.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Tabel Mahasiswa',
            },
        ),
    ]
