# Generated by Django 5.2.12 on 2026-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampus_app', '0002_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('isi_pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
