# Generated by Django 5.2.12 on 2026-05-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampus_app', '0003_pesan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mahasiswa',
            new_name='Pengunjung',
        ),
        migrations.AlterModelOptions(
            name='pengunjung',
            options={'verbose_name_plural': 'Tabel Pengunjung'},
        ),
        migrations.AlterModelOptions(
            name='pesan',
            options={'verbose_name_plural': 'Pesan'},
        ),
    ]
