# Generated by Django 5.2.12 on 2026-05-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampus_app', '0004_rename_mahasiswa_pengunjung_alter_pengunjung_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengunjung',
            old_name='id_jurusan',
            new_name='jurusan',
        ),
    ]
