# Generated by Django 5.2.12 on 2026-05-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampus_app', '0005_rename_id_jurusan_pengunjung_jurusan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengunjung',
            old_name='nim',
            new_name='id',
        ),
    ]
